name: Build iOS Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Theos and iOS SDK
      uses: upm-center/setup-theos@v1
      with:
        theos-version: 'master'

    - name: Build Tweak Package
      run: |
        make package FINALPACKAGE=1
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Tweak-Deb
        path: packages/*.deb
