name: Build iOS Tweak
on: [push, pull_request]

env:
  THEOS: /home/runner/theos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Theos Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y lzma liblzma-dev build-essential git ccache curl unzip
        bash -c "$(curl -fsSL https://githubusercontent.com)"

    - name: Download iOS SDK
      run: |
        mkdir -p $THEOS/sdks
        curl -LO https://github.com
        unzip master.zip
        mv sdks-master/* $THEOS/sdks/
        rm -rf sdks-master master.zip

    - name: Build Tweak Package
      run: |
        make package FINALPACKAGE=1 SYSROOT=$THEOS/sdks/iPhoneOS14.5.sdk
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: iOS-Tweak-Deb
        path: packages/*.deb
